/**
 * AUTO-GENERATED BY LOBSTAH-BUILDER
 * Source: SQLite Warehouse
 */

export const traderDashboardData = {
    "address": "0x43372356634781eea88d61bbdd7824cdce958882",
    "lastUpdated": "2026-02-05T17:03:35.232Z",
    "stats": {
        "totalTrades": 100,
        "activePositions": 10,
        "totalActivePnL": 1177680.9832648411
    },
    "summary": {
        "totalGain": 1201046.173105841,
        "totalLoss": 23365.189841,
        "netPnl": 1177680.9832648411,
        "numTrades": 100
    },
    "positions": [
        {
            "title": "LoL: Invictus Gaming vs Weibo Gaming (BO3) - LPL Group Ascend",
            "slug": "lol-invictus-gaming-vs-weibo-gaming-bo3---lpl-group-ascend",
            "size": 19,
            "avgPrice": 0,
            "percentPnl": 0
        },
        {
            "title": "Will Bitcoin dip to $35,000 in February?",
            "slug": "will-bitcoin-dip-to-35000-in-february",
            "size": 11,
            "avgPrice": 0,
            "percentPnl": 0
        },
        {
            "title": "Binghamton Bearcats vs. UMBC Retrievers: O/U 139.5",
            "slug": "binghamton-bearcats-vs-umbc-retrievers-ou-1395",
            "size": 10,
            "avgPrice": 0,
            "percentPnl": 0
        },
        {
            "title": "LoL: JD Gaming vs Top Esports (BO3) - LPL Group Ascend",
            "slug": "lol-jd-gaming-vs-top-esports-bo3---lpl-group-ascend",
            "size": 10,
            "avgPrice": 0,
            "percentPnl": 0
        },
        {
            "title": "Canadiens vs. Jets",
            "slug": "canadiens-vs-jets",
            "size": 8,
            "avgPrice": 0,
            "percentPnl": 0
        },
        {
            "title": "EdgeX FDV above $3B one day after launch?",
            "slug": "edgex-fdv-above-3b-one-day-after-launch",
            "size": 8,
            "avgPrice": 0,
            "percentPnl": 0
        },
        {
            "title": "US strikes Iran by June 30, 2026?",
            "slug": "us-strikes-iran-by-june-30-2026",
            "size": 8,
            "avgPrice": 0,
            "percentPnl": 0
        },
        {
            "title": "U.S. anti-cartel ground operation in Mexico by January 31?",
            "slug": "us-anti-cartel-ground-operation-in-mexico-by-january-31",
            "size": 7,
            "avgPrice": 0,
            "percentPnl": 0
        },
        {
            "title": "Valorant: Pcific Esports vs ULF Esports (BO3) - VCT EMEA Kickoff Playoffs",
            "slug": "valorant-pcific-esports-vs-ulf-esports-bo3---vct-emea-kickoff-playoffs",
            "size": 6,
            "avgPrice": 0,
            "percentPnl": 0
        },
        {
            "title": "LoL: Weibo Gaming vs Anyone's Legend (BO3) - LPL Group Ascend",
            "slug": "lol-weibo-gaming-vs-anyones-legend-bo3---lpl-group-ascend",
            "size": 5,
            "avgPrice": 0,
            "percentPnl": 0
        }
    ],
    "trades": [],
    "topMarkets": [
        {
            "question": "LoL: Invictus Gaming vs Weibo Gaming (BO3) - LPL Group Ascend",
            "trades": 19,
            "pnl": -3183.2975829999996
        },
        {
            "question": "Will Bitcoin dip to $35,000 in February?",
            "trades": 11,
            "pnl": 1297.355203
        },
        {
            "question": "Binghamton Bearcats vs. UMBC Retrievers: O/U 139.5",
            "trades": 10,
            "pnl": 8690.574707
        },
        {
            "question": "LoL: JD Gaming vs Top Esports (BO3) - LPL Group Ascend",
            "trades": 10,
            "pnl": -635.615178
        },
        {
            "question": "Canadiens vs. Jets",
            "trades": 8,
            "pnl": 2416.8568
        },
        {
            "question": "EdgeX FDV above $3B one day after launch?",
            "trades": 8,
            "pnl": 996.7719999999999
        },
        {
            "question": "US strikes Iran by June 30, 2026?",
            "trades": 8,
            "pnl": 580.8191
        },
        {
            "question": "U.S. anti-cartel ground operation in Mexico by January 31?",
            "trades": 7,
            "pnl": 40502.81305
        },
        {
            "question": "Valorant: Pcific Esports vs ULF Esports (BO3) - VCT EMEA Kickoff Playoffs",
            "trades": 6,
            "pnl": 481.53596000000005
        },
        {
            "question": "LoL: Weibo Gaming vs Anyone's Legend (BO3) - LPL Group Ascend",
            "trades": 5,
            "pnl": -557.3863
        }
    ]
};
