/**
 * AUTO-GENERATED BY LOBSTAH-BUILDER
 * Source: SQLite Warehouse
 */

export const traderDashboardData = {
    "address": "0x43372356634781eea88d61bbdd7824cdce958882",
    "lastUpdated": "2026-02-05T17:07:03.424Z",
    "stats": {
        "totalTrades": 2000,
        "activePositions": 10,
        "totalActivePnL": 1394341.767584841
    },
    "summary": {
        "totalGain": 2031382.576561841,
        "totalLoss": 637040.808977,
        "netPnl": 1394341.767584841,
        "numTrades": 2000
    },
    "positions": [
        {
            "title": "LoL: Weibo Gaming vs Anyone's Legend (BO3) - LPL Group Ascend",
            "slug": "lol-weibo-gaming-vs-anyones-legend-bo3---lpl-group-ascend",
            "size": 315,
            "avgPrice": 0,
            "percentPnl": 0
        },
        {
            "title": "Magic vs. Thunder",
            "slug": "magic-vs-thunder",
            "size": 115,
            "avgPrice": 0,
            "percentPnl": 0
        },
        {
            "title": "76ers vs. Clippers",
            "slug": "76ers-vs-clippers",
            "size": 111,
            "avgPrice": 0,
            "percentPnl": 0
        },
        {
            "title": "LoL: OKSavingsBank BRION vs BNK FEARX (BO3)",
            "slug": "lol-oksavingsbank-brion-vs-bnk-fearx-bo3",
            "size": 76,
            "avgPrice": 0,
            "percentPnl": 0
        },
        {
            "title": "LoL: Invictus Gaming vs JD Gaming (BO3) - LPL Group Ascend",
            "slug": "lol-invictus-gaming-vs-jd-gaming-bo3---lpl-group-ascend",
            "size": 67,
            "avgPrice": 0,
            "percentPnl": 0
        },
        {
            "title": "Creighton Bluejays vs. Georgetown Hoyas",
            "slug": "creighton-bluejays-vs-georgetown-hoyas",
            "size": 59,
            "avgPrice": 0,
            "percentPnl": 0
        },
        {
            "title": "U.S. anti-cartel ground operation in Mexico by January 31?",
            "slug": "us-anti-cartel-ground-operation-in-mexico-by-january-31",
            "size": 56,
            "avgPrice": 0,
            "percentPnl": 0
        },
        {
            "title": "LoL: JD Gaming vs Top Esports (BO3) - LPL Group Ascend",
            "slug": "lol-jd-gaming-vs-top-esports-bo3---lpl-group-ascend",
            "size": 53,
            "avgPrice": 0,
            "percentPnl": 0
        },
        {
            "title": "Bulls vs. Bucks",
            "slug": "bulls-vs-bucks",
            "size": 47,
            "avgPrice": 0,
            "percentPnl": 0
        },
        {
            "title": "North Texas Mean Green vs. Rice Owls",
            "slug": "north-texas-mean-green-vs-rice-owls",
            "size": 45,
            "avgPrice": 0,
            "percentPnl": 0
        }
    ],
    "trades": [],
    "topMarkets": [
        {
            "question": "LoL: Weibo Gaming vs Anyone's Legend (BO3) - LPL Group Ascend",
            "trades": 315,
            "pnl": 10368.284280000002
        },
        {
            "question": "Magic vs. Thunder",
            "trades": 115,
            "pnl": 46687.85541
        },
        {
            "question": "76ers vs. Clippers",
            "trades": 111,
            "pnl": 16970.458307
        },
        {
            "question": "LoL: OKSavingsBank BRION vs BNK FEARX (BO3)",
            "trades": 76,
            "pnl": -12750.27392
        },
        {
            "question": "LoL: Invictus Gaming vs JD Gaming (BO3) - LPL Group Ascend",
            "trades": 67,
            "pnl": 6514.462904000001
        },
        {
            "question": "Creighton Bluejays vs. Georgetown Hoyas",
            "trades": 59,
            "pnl": 6202.028786999999
        },
        {
            "question": "U.S. anti-cartel ground operation in Mexico by January 31?",
            "trades": 56,
            "pnl": 340710.357382
        },
        {
            "question": "LoL: JD Gaming vs Top Esports (BO3) - LPL Group Ascend",
            "trades": 53,
            "pnl": -58.475582999999915
        },
        {
            "question": "Bulls vs. Bucks",
            "trades": 47,
            "pnl": 23549.63679
        },
        {
            "question": "North Texas Mean Green vs. Rice Owls",
            "trades": 45,
            "pnl": 8499.572585
        }
    ]
};
