import { open } from 'sqlite';
import sqlite3 from 'sqlite3';
import * as path from 'path';
import * as fs from 'fs';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const TARGET_TRADERS = [
    "0x63ce342161250d705dc0b16df89036c8e5f9ba9a",
    "0x43372356634781eea88d61bbdd7824cdce958882"
];

const SCALING_FACTOR = 4.546;

async function generateDashboards() {
    const dbPath = path.resolve(__dirname, '../../data/lobstah.db');
    const db = await open({
        filename: dbPath,
        driver: sqlite3.Database
    });

    console.log("🦞 LobstahBuilder: Generating Spotlight Dashboards...");

    for (const address of TARGET_TRADERS) {
        const addr = address.toLowerCase();
        console.log(`Processing ${addr}...`);

        const stats = await db.get(`
            SELECT 
                COUNT(t.id) as trade_count,
                (
                    (SUM(CASE 
                        WHEN t.side = 'MAKER' AND t.maker_asset_id = '0' THEN t.maker_amount 
                        WHEN t.side = 'TAKER' AND t.taker_asset_id = '0' THEN t.taker_amount 
                        ELSE 0 
                    END)) + 
                    (COALESCE(p.payout_total, 0) / ${SCALING_FACTOR})
                ) / 1000000.0 as gain,
                (SUM(CASE 
                    WHEN t.side = 'MAKER' AND t.maker_asset_id != '0' THEN t.taker_amount 
                    WHEN t.side = 'TAKER' AND t.taker_asset_id != '0' THEN t.maker_amount 
                    ELSE 0 
                END)) / 1000000.0 as loss
            FROM trades t
            LEFT JOIN (
                SELECT trader_address, SUM(amount) as payout_total 
                FROM payouts 
                GROUP BY trader_address
            ) p ON t.trader_address = p.trader_address
            WHERE t.trader_address = ?
        `, [addr]);

        const topMarkets = await db.all(`
            SELECT 
                m.question,
                m.condition_id,
                COUNT(t.id) as count,
                SUM(CASE 
                    WHEN side = 'MAKER' AND maker_asset_id = '0' THEN maker_amount 
                    WHEN side = 'TAKER' AND taker_asset_id = '0' THEN taker_amount 
                    ELSE 0 
                END) / 1000000.0 as cash_in,
                SUM(CASE 
                    WHEN side = 'MAKER' AND maker_asset_id != '0' THEN taker_amount 
                    WHEN side = 'TAKER' AND taker_asset_id != '0' THEN maker_amount 
                    ELSE 0 
                END) / 1000000.0 as cash_out
            FROM trades t
            JOIN markets m ON t.market_condition_id = m.condition_id
            WHERE t.trader_address = ?
            GROUP BY m.condition_id
            ORDER BY count DESC
            LIMIT 10
        `, [addr]);

        const dashboardData = {
            address: addr,
            lastUpdated: new Date().toISOString(),
            stats: {
                totalTrades: stats.trade_count,
                activePositions: topMarkets.length,
                totalActivePnL: stats.gain - stats.loss
            },
            summary: {
                totalGain: stats.gain,
                totalLoss: stats.loss,
                netPnl: stats.gain - stats.loss,
                numTrades: stats.trade_count
            },
            positions: topMarkets.map(m => ({
                title: m.question || "Unknown Market",
                conditionId: m.condition_id,
                slug: m.question ? m.question.toLowerCase().replace(/ /g, '-').replace(/[^a-z0-9-]/g, '') : null,
                size: m.count,
                avgPrice: 0,
                percentPnl: 0
            })),
            trades: [],
            topMarkets: topMarkets.map(m => ({
                question: m.question,
                trades: m.count,
                pnl: m.cash_in - m.cash_out
            }))
        };

        const outputDir = path.resolve(__dirname, `../../web/content/docs/lobstah-trader/trader-spotlights/${addr}`);
        if (!fs.existsSync(outputDir)) {
            fs.mkdirSync(outputDir, { recursive: true });
        }

        const outputPath = path.join(outputDir, 'data.ts');
        const fileContent = `/**\n * AUTO-GENERATED BY LOBSTAH-BUILDER\n * Source: SQLite Warehouse\n */\n\nexport const traderDashboardData = ${JSON.stringify(dashboardData, null, 4)};\n`;

        fs.writeFileSync(outputPath, fileContent);
        console.log(`✅ Dashboard data written to: ${outputPath}`);
    }

    await db.close();
}

generateDashboards();
