import { open } from 'sqlite';
import sqlite3 from 'sqlite3';
import * as path from 'path';
import * as fs from 'fs';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// Target traders to generate dashboards for
const TARGET_TRADERS = [
    "0x63ce342161250d705dc0b16df89036c8e5f9ba9a"
];

const SCALING_FACTOR = 4.546;

async function generateDashboards() {
    const dbPath = path.resolve(__dirname, '../../data/lobstah.db');
    const db = await open({
        filename: dbPath,
        driver: sqlite3.Database
    });

    console.log("🦞 LobstahBuilder: Generating Spotlight Dashboards...");

    for (const address of TARGET_TRADERS) {
        const addr = address.toLowerCase();
        console.log(`Processing ${addr}...`);

        // 1. Fetch Aggregated Stats
        const stats = await db.get(`
            WITH trade_flows AS (
                SELECT 
                    SUM(CASE 
                        WHEN side = 'MAKER' AND maker_asset_id = '0' THEN maker_amount 
                        WHEN side = 'TAKER' AND taker_asset_id = '0' THEN taker_amount 
                        ELSE 0 
                    END) as received,
                    SUM(CASE 
                        WHEN side = 'MAKER' AND maker_asset_id != '0' THEN taker_amount 
                        WHEN side = 'TAKER' AND taker_asset_id != '0' THEN maker_amount 
                        ELSE 0 
                    END) as spent
                FROM trades WHERE trader_address = ?
            ),
            payout_flows AS (
                SELECT SUM(amount) as payout FROM payouts
            )
            SELECT 
                (received + (payout / ?)) / 1000000.0 as total_gain,
                spent / 1000000.0 as total_loss,
                (SELECT COUNT(*) FROM trades WHERE trader_address = ?) as trade_count
            FROM trade_flows, payout_flows
        `, [addr, SCALING_FACTOR, addr]);

        // 2. Fetch Top Markets
        const topMarkets = await db.all(`
            SELECT 
                m.question,
                COUNT(t.id) as count,
                SUM(CASE 
                    WHEN side = 'MAKER' AND maker_asset_id = '0' THEN maker_amount 
                    WHEN side = 'TAKER' AND taker_asset_id = '0' THEN taker_amount 
                    ELSE 0 
                END) / 1000000.0 as cash_in,
                SUM(CASE 
                    WHEN side = 'MAKER' AND maker_asset_id != '0' THEN taker_amount 
                    WHEN side = 'TAKER' AND taker_asset_id != '0' THEN maker_amount 
                    ELSE 0 
                END) / 1000000.0 as cash_out
            FROM trades t
            JOIN markets m ON t.market_condition_id = m.condition_id
            WHERE t.trader_address = ?
            GROUP BY m.condition_id
            ORDER BY count DESC
            LIMIT 10
        `, [addr]);

        // 3. Prepare the Output Data
        const dashboardData = {
            address: addr,
            lastUpdated: new Date().toISOString(),
            summary: {
                totalGain: stats.total_gain,
                totalLoss: stats.total_loss,
                netPnl: stats.total_gain - stats.total_loss,
                numTrades: stats.trade_count
            },
            topMarkets: topMarkets.map(m => ({
                question: m.question,
                trades: m.count,
                pnl: m.cash_in - m.cash_out
            }))
        };

        // 4. Write to the respective directory
        const outputDir = path.resolve(__dirname, `../../web/content/docs/lobstah-trader/trader-spotlights/${addr}`);
        if (!fs.existsSync(outputDir)) {
            fs.mkdirSync(outputDir, { recursive: true });
        }

        const outputPath = path.join(outputDir, 'data.ts');
        const fileContent = `/**\n * AUTO-GENERATED BY LOBSTAH-BUILDER\n * Source: SQLite Warehouse\n */\n\nexport const traderDashboardData = ${JSON.stringify(dashboardData, null, 4)};\n`;

        fs.writeFileSync(outputPath, fileContent);
        console.log(`✅ Dashboard data written to: ${outputPath}`);
    }

    await db.close();
}

generateDashboards();
