/**
 * AUTO-GENERATED BY LOBSTAH-BUILDER
 * Source: SQLite Warehouse
 */

export const traderDashboardData = {
    "address": "0x63ce342161250d705dc0b16df89036c8e5f9ba9a",
    "lastUpdated": "2026-02-05T16:45:55.827Z",
    "summary": {
        "totalGain": 1529159.183385841,
        "totalLoss": 393867.659918,
        "netPnl": 1135291.523467841,
        "numTrades": 34398
    },
    "topMarkets": [
        {
            "question": "Bitcoin Up or Down - February 5, 9:30AM-9:45AM ET",
            "trades": 2854,
            "pnl": 2568.368423
        },
        {
            "question": "Bitcoin Up or Down - February 5, 10:15AM-10:30AM ET",
            "trades": 2312,
            "pnl": 11170.748849
        },
        {
            "question": "Ethereum Up or Down - February 5, 9:30AM-9:45AM ET",
            "trades": 1940,
            "pnl": 17641.688213
        },
        {
            "question": "Bitcoin Up or Down - February 5, 7:45AM-8:00AM ET",
            "trades": 1573,
            "pnl": 702.2464570000011
        },
        {
            "question": "Bitcoin Up or Down - February 5, 7:30AM-7:45AM ET",
            "trades": 1551,
            "pnl": -5218.449344999999
        },
        {
            "question": "Bitcoin Up or Down - February 5, 8:30AM-8:45AM ET",
            "trades": 1380,
            "pnl": 2507.9128530000016
        },
        {
            "question": "Bitcoin Up or Down - February 5, 8:15AM-8:30AM ET",
            "trades": 1004,
            "pnl": 1452.8563270000004
        },
        {
            "question": "Bitcoin Up or Down - February 5, 10:45AM-11:00AM ET",
            "trades": 908,
            "pnl": 1496.5590580000007
        },
        {
            "question": "Ethereum Up or Down - February 5, 8:30AM-8:45AM ET",
            "trades": 905,
            "pnl": 6447.717807000001
        },
        {
            "question": "Bitcoin Up or Down - February 5, 9:00AM-9:15AM ET",
            "trades": 901,
            "pnl": 3414.939466
        }
    ]
};
