import fs from 'fs';
import path from 'path';

const TRADER_ADDRESS = "0x63ce342161250d705dc0b16df89036c8e5f9ba9a";
const DATA_API = "https://data-api.polymarket.com";
const OUTPUT_DIR = path.join(process.cwd(), "web/content/docs/lobstah-trader/trader-spotlights", TRADER_ADDRESS);
const OUTPUT_FILE = path.join(OUTPUT_DIR, "predictions.ts");

async function scout() {
    console.log(`🦞 LobstahScout: Deep-diving trader ${TRADER_ADDRESS}...`);

    try {
        // 1. Fetch Positions
        const posRes = await fetch(`${DATA_API}/positions?user=${TRADER_ADDRESS}`);
        const positions = await posRes.json();

        // 2. Paginated Fetch for Trades
        let allTrades: any[] = [];
        let offset = 0;
        const limit = 100;
        let hasMore = true;

        while (hasMore) {
            console.log(`📡 Fetching trades (offset: ${offset})...`);
            const tradeRes = await fetch(`${DATA_API}/trades?user=${TRADER_ADDRESS}&limit=${limit}&offset=${offset}`);
            const batch = await tradeRes.json();
            
            if (batch.length > 0) {
                allTrades = allTrades.concat(batch);
                offset += limit;
                // Optional: Stop if we hit a massive amount for now to prevent OOM
                if (allTrades.length >= 15000) {
                    console.log("⚠️ Limit reached (15k). Stopping.");
                    hasMore = false;
                }
            } else {
                hasMore = false;
            }
        }

        const trades = allTrades;

        // 3. Simple Stats Calculation
        const stats = {
            totalTrades: trades.length,
            activePositions: positions.length,
            totalPnL: positions.reduce((acc: number, p: any) => acc + (p.cashPnl || 0), 0),
            winRate: 0 // Logic for historical win rate would go here based on resolved trades
        };

        // 4. Generate the predictions.ts content
        const fileContent = `/**
 * AUTO-GENERATED BY LOBSTAH-SCOUT
 * Last Updated: ${new Date().toISOString()}
 */

export const traderData = {
    address: "${TRADER_ADDRESS}",
    stats: ${JSON.stringify(stats, null, 4)},
    positions: ${JSON.stringify(positions, null, 4)},
    trades: ${JSON.stringify(trades, null, 4)}
};
`;

        // 5. Write to file
        if (!fs.existsSync(OUTPUT_DIR)) {
            fs.mkdirSync(OUTPUT_DIR, { recursive: true });
        }
        fs.writeFileSync(OUTPUT_FILE, fileContent);

        console.log(`✅ Success! Dashboard data written to: ${OUTPUT_FILE}`);
        console.log(`📊 Summary: ${stats.totalTrades} trades, ${stats.activePositions} active positions.`);

    } catch (error) {
        console.error("❌ Failed to scout trader:", error);
    }
}

scout();
